### ISSUE TITLE
Option to ignore external libraries

### ISSUE THREAD

**Issue by s093294** [SitePen/dts-generator#54] opened 2016-01-04 21:27 UTC
I have a module that depends on 

`import Q = require("q");`

which the generated d.ts before combining looks like 
```
import Q = require("q");
import implicitRequestOptions = require("./implicitRequestOptions");
import oAuthResult = require("./oAuthResult");
declare class oAuthClient {
    url: any;
    constructor(url?: any);
    setUrl(url: any): void;
    createSilentImplicitFlow(clientid: any, callback: any, scope: any, responseType?: string): Q.Promise<{}>;
    createImplicitFlowRequest(clientid: any, callback: any, scope: any, options: implicitRequestOptions): {
        url: string;
        state: string;
        nonce: string;
    };
    parseResult(queryStringOrParams: any): oAuthResult;
}
export = oAuthClient;
```
which causes 

```
Running "dtsGenerator:default" (dtsGenerator) task
Warning: Cannot read property 'kind' of undefined Use --force to continue.
Aborted due to warnings.
```

Is there a way to tell it to simply ignore the `import Q = require("q");` and rely on the consumer library also to include "q" or how would i best handle this situation.

**Comment by s093294** [comment] 2016-01-04 22:12
I added a PR that checks that parent is defined, with the PR everything behaves as expected

**Comment by dougludlow** [comment] 2016-01-26 19:48
Ha ha, looks like #58 is a duplicate of this. I ran into the same issue, and put a pr for the same fix.

**Comment by kitsonk** [comment] 2016-03-01 14:37
Closing as dupe of #58

**Closed by kitsonk** 2016-03-01 14:37 UTC
Labels: enhancement
